//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebViettel.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QL_PRODUCTSEntities : DbContext
    {
        public QL_PRODUCTSEntities()
            : base("name=QL_PRODUCTSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TB_Category> TB_Category { get; set; }
        public virtual DbSet<TB_CTDH> TB_CTDH { get; set; }
        public virtual DbSet<TB_DONDATHANG> TB_DONDATHANG { get; set; }
        public virtual DbSet<TB_SanPham> TB_SanPham { get; set; }
        public virtual DbSet<TB_GUESTS> TB_GUESTS { get; set; }
    }
}
