//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebViettel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_DONDATHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_DONDATHANG()
        {
            this.TB_CTDH = new HashSet<TB_CTDH>();
        }

        public string MADON { get; set; }
        public string TEN_KH { get; set; }
        public string USER_PHONE { get; set; }
        public string AMOUNT { get; set; }
        public string MESSEAGE { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_CTDH> TB_CTDH { get; set; }
    }
}
