//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebViettel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_SanPham()
        {
            this.TB_CTDH = new HashSet<TB_CTDH>();
        }

        public string MA_SPHAM { get; set; }
        public string MaLoai { get; set; }
        public string Ten_SP { get; set; }
        public string Hinh { get; set; }
        public string DT_DEN { get; set; }
        public string DT_PIN { get; set; }
        public string CONG_SUAT_DEN { get; set; }
        public string SL_CHIPLEAD { get; set; }
        public string CONG_SUAT_PIN { get; set; }
        public string DUNG_LUONG_PIN { get; set; }
        public string LIGHT_RANGE { get; set; }
        public string LIGHT_TIME { get; set; }
        public int PRIDE { get; set; }

        public virtual TB_Category TB_Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_CTDH> TB_CTDH { get; set; }
    }
}
